### ISSUE TITLE
GetFeatureInfo

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms-client13#12]
udig is the reference implementation.  4.1b is passing the test. (0.8 and 0.9)

1.5.0 RC1 is not passing due to CRS issue. This seems to be a problem with uDIG.

```
 Assertion: Each of the mandatory parameters shall be present, (SERVICE=WMS and REQUEST=GetCapabilities). 
URL: http://localhost:8080/teamengine/monitor/2?SERVICE=WMS&INFO_FORMAT=text/html&LAYERS=cite:Terrain&FORMAT=image/png&HEIGHT=635&J=190&REQUEST=GetFeatureInfo&I=513&WIDTH=609&BBOX=-7.067037789850584,-2.5798738555450242,1.7154731509574557,6.577588291274525&STYLES=terrain1&QUERY_LAYERS=cite:Terrain&VERSION=1.3.0 
Reason For Failure: Did not provide the CRS parameter.
```

![wms13client](https://cloud.githubusercontent.com/assets/3738898/8207313/a607e3a4-14ce-11e5-8965-6640003a1938.jpg)

**Comment by bermud** [comment]
@keshav-nangare, please take a look at this issue. let me know if you can reproduce it.

**Comment by keshavnangare** [comment]
This issue is not reproducible. We have tested the wms-client13 [1.2] with teamengine 4.6, it is working fine.

Following is the Test result: 

![wms_client_test_result](https://cloud.githubusercontent.com/assets/14732650/14677312/c3d1e472-072e-11e6-9dd7-787914449921.png)

![wms_client_udig](https://cloud.githubusercontent.com/assets/14732650/14677338/deeea9e8-072e-11e6-91d4-2e7a2f2cdffa.png)
