### ISSUE TITLE
getFeatureInfo - Failure

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms-client13#16]
GetFeatureInfo is failing is not clear why

Here are logs
http://cite.opengeospatial.org/pub/cite/files/wms-client-13-20150922.zip

Here is the code:

```
class getFeatureInfoRequestAsync extends AsyncTask<Void, Void, Void>
{
String URL="http://cite.deegree.org/deegree-webservices-3.3.14-2/services/wms?              SERVICE=WMS&INFO_FORMAT=text/html&LAYERS=cite:Terrain&CRS=EPSG:4326&FORMAT=image/png&HEIGHT=377&J=315&REQUEST=GetFeatureInfo&I=467&WIDTH=919&BBOX=-8.53183023872679,-1.0,8.53183023872679,6.0&STYLES=terrain1&QUERY_LAYERS=cite:Terrain&VERSION=1.3.0";
@Override
protected void onPreExecute() {
// TODO Auto-generated method stub
super.onPreExecute();
}
@Override
protected Void doInBackground(Void... params) {
StringBuilder stringBuilder = new StringBuilder();
HttpClient httpClient = new DefaultHttpClient();
HttpGet httpGet = new HttpGet(URL);
try {
HttpResponse response = httpClient.execute(httpGet);
//headers = null;
       //headers = response.getAllHeaders();
StatusLine statusLine = response.getStatusLine();
int statusCode = statusLine.getStatusCode();
if (statusCode == 200) {
HttpEntity entity = response.getEntity();
InputStream inputStream = entity.getContent();
BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
String line;
while ((line = reader.readLine()) != null) {
stringBuilder.append(line);
}
inputStream.close();
} else {
Log.d("JSON", "Failed to download file");
}
} catch (Exception e) {
Log.d("readJSONFeed", e.getLocalizedMessage());
}
return null;  
}
protected void onPostExecute(Void result) 
{
try {
Toast.makeText(MainActivitySidebar.this, "Perfect", Toast.LENGTH_LONG);
} 
catch (Exception e) {
Toast.makeText(MainActivitySidebar.this, e.getLocalizedMessage(), Toast.LENGTH_LONG).show();
} 
};
}
```

**Comment by upendra-sachan** [comment]
We tested the client request's URL and we found that they used WMS-server URL for testing GetFeatureInfo and it produced the result but, which was not related to the current session of running test. They have to pass the monitor URL instead of the WMS-server URL and its parameter.

We have tested the same URL at our end, with Monitor-URL of current running test session, it works fine in this case.

Example:

Instead of this URL:
**http://cite.deegree.org/deegree-webservices-3.3.14-2/services/wms**?SERVICE=WMS&INFO_FORMAT=text/html&LAYERS=cite:Terrain&CRS=EPSG:4326&FORMAT=image/png&HEIGHT=377&J=315&REQUEST=GetFeatureInfo&I=467&WIDTH=919&BBOX=-8.53183023872679,-1.0,8.53183023872679,6.0&STYLES=terrain1&QUERY_LAYERS=cite:Terrain&VERSION=1.3.0

Use this:
**{monitor-URL}**?SERVICE=WMS&INFO_FORMAT=text/html&LAYERS=cite:Terrain&CRS=EPSG:4326&FORMAT=image/png&HEIGHT=377&J=315&REQUEST=GetFeatureInfo&I=467&WIDTH=919&BBOX=-8.53183023872679,-1.0,8.53183023872679,6.0&STYLES=terrain1&QUERY_LAYERS=cite:Terrain&VERSION=1.3.0

Where {monitor-URL} is live running test URL which need to be passed dynamically. We can't hard-code it there.

**Comment by mickmaku** [comment]
Hello there.

I have tested the GetFeatureInfo as suggested. I am not sure if I understood the correct syntax for the monitor-URL. What I have just use is:

http://cite.opengeospatial.org/teamengine/monitor/X?SERVICE=WMS&INFO_FORMAT=text/html&LAYERS=cite:Terrain&CRS=EPSG:4326&FORMAT=image/png&HEIGHT=377&J=315&REQUEST=GetFeatureInfo&I=467&WIDTH=919&BBOX=-8.53183023872679,-1.0,8.53183023872679,6.0&STYLES=terrain1&QUERY_LAYERS=cite:Terrain&VERSION=1.3.0

Most certainly, the value of X is dynamic for each testing session and thus is subjected to change every time i compile the application. Is this URL acceptable? 

It has just returned status code = 500

Thanks for your help.

**Comment by keshavnangare** [comment]
Yes,the monitor URL is changed every time dynamically, i.e. value of X in the URL is always changed.

Example:- 

If monitor URL is http://localhost:8080/teamengine/monitor/0 
then request URL are:-
For GetCapability request :- http://localhost:8080/teamengine/monitor/0?{Parameters}
For GetMap request :- http://localhost:8080/teamengine/monitor/1?{Parameters}
For GetFeatureInfo request :- http://localhost:8080/teamengine/monitor/2?{Parameters}

Now, if you run again WMS-client1.3 then monitor-URL is http://localhost:8080/teamengine/monitor/3
So, GetCapability is :- http://localhost:8080/teamengine/monitor/3?{Parameters}
GetMap is :- http://localhost:8080/teamengine/monitor/4?{Parameters}
GetFeatureInfo is :- http://localhost:8080/teamengine/monitor/5?{Parameters}

and so on..... till you restart the tomcat.

**Comment by mickmaku** [comment]
Okay. So do i have to consider adding 2 on the X value before constructing the URL for GetFeatureInfo? What i have been doing is to simply take the generated monitor-URL and simply append the:
?SERVICE=WMS&INFO_FORMAT=text/html&LAYERS=cite:Terrain&CRS=EPSG:4326&FORMAT=image/png&HEIGHT=377&J=315&REQUEST=GetFeatureInfo&I=467&WIDTH=919&BBOX=-8.53183023872679,-1.0,8.53183023872679,6.0&STYLES=terrain1&QUERY_LAYERS=cite:Terrain&VERSION=1.3.0

On the above post, i realized there are actually 0,1 and 2 to access the different capabilities. 

Or i simply pass the generated monitor URL and the testing engine does the reassigning for GetCapbilities, GetMap and GetFeatureInfo?

**Comment by upendra-sachan** [comment]
Yes you are thinking right,
According the monitor URL,
For GetCapabiltiy: adding 0 on the X value
GetMap: adding 1 on the X value
GetFeatureInfo: adding 2 on the X value.

**Comment by mickmaku** [comment]
YES! That certainly did the job. Thanks a lot.
