### ISSUE TITLE
Adding multiple layers in QGIS is not recognized 

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wms-client13#37]
This is similar to #34 but QGIS does **not** send one request with multiple layers but one request per layer.

But the result is the same: Only one layer is recognized as requested and in the result view only one layer change the status.

**Comment by lgoltz** [comment]
@keshav-nangare 
Can you test the PR #40 on windows, after moving the code from teamengine to the ets (https://github.com/opengeospatial/ets-wms-client13/pull/40#issuecomment-469652202).

**Comment by keshavnangare** [comment]
@lgoltz 

While testing this PR #40 I got the following  error:
`java.net.MalformedURLException: no protocol: ../../../../images/minus.png`
This issue is already reported here: https://github.com/opengeospatial/teamengine/issues/385

The PR https://github.com/opengeospatial/teamengine/pull/386 should be merged in master with the changes of wms-client

**Comment by keshavnangare** [comment]
@lgoltz 

I have tested PR #40 successfully and it's working on windows as well.
