### ISSUE TITLE
When stopping the test without any request the result is incorrect and missing information

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms-client13#7]
Tested TE https://github.com/opengeospatial/teamengine/commit/13b8e3b2b34034cc81aa31848111e31b91bee1bd

WMS 1.3 client test v 0.6

![error](https://cloud.githubusercontent.com/assets/3738898/6307695/f6b97da4-b90b-11e4-959b-92d1c37b2888.jpg)

**Comment by bermud** [comment]
It seems is an error when stopping the test from the upper right stop button. The stop button at the bottom of the test works fine. Please fix any issues on the upper right test button and change the behavior of the bottom stop button  to match the behavior of the upper right button (i.e. make the same call).

**Comment by upendra-sachan** [comment]
Hi Luis,

Yes, It is a issue for all test when stopping the test from the upper right
stop. The stop button at bottom of the test works fine. Because when we
click upper right stop it call this method:

if (operation.equals("Stop")) {
                response.setContentType("text/xml");
                TECore core = (TECore) session.getAttribute("testsession");
                if (core != null) {
                    _core.stopThread();_
                    session.removeAttribute("testsession");
                    out.println("<stopped/>");
                } else {
                    out.println("<message>Could not retrieve core
object</message>");
                }
            }

Which actually sleeps the thread infinitely. We cant get the test status
recordings at this place, since tests run in respective projects.

 We can trigger the method for bottom stop test button from upper stop test
button. So for this we can apply this solution:
- Give a common id("_stopTest_") to all stop button at bottom of the
  test.
- Trigger this button from upper right stop button for click event.
- After clicking upper right stop button it automatically internally
  call bottom stop button and apply all operation.

Thanks.

---

Upendra Sachan
Mindstix Software Labs
http://www.mindstix.com

_Email:_ upendra.sachan@mindstix.com blah@mindstix.com
_Phone:_ +91 8446253174
_Skype:_ upendra.sachan1

**Comment by bermud** [comment]
Why don't you add another attribute like testid to the session

If the testid !=null,
    call the new stop process
If not, behave as usual

**Comment by bermud** [comment]
Fixed here: https://github.com/opengeospatial/teamengine/commit/9539472571fceb938fad6c094e32c50dabaed000
